Repository amunra2/team-dev-bmstu-iu7, pull requests merged in 2023-05, with the labels that each got.

#24 Ошибки линтера E127 и W504 добавлены в исключения
  cfg/linter.cfg
Labels: bug

#21 #18: Разработан компонент синхронизации данных
  .env.example
  requirements.txt
  sync/addition.py
  sync/codes.py
  sync/deletion.py
  sync/sync.py
Labels: enhancement

#25 #25: Добавлено API для доступа к базе данных
  .env.example
  backend/app.py
  backend/migrations/versions/adbe96599a1e_init_cascade_relationships.py
  backend/models/__init__.py
  backend/models/classroom.py
  backend/models/schedule_class.py
  backend/models/state.py
  backend/resources/class_api.py
  backend/resources/classroom_api.py
  backend/resources/state_api.py
  backend/schemes/class_schema.py
  backend/schemes/classroom_schema.py
  backend/schemes/state_schema.py
  backend/swagger/classes_delete.yml
  backend/swagger/classes_get_all.yml
  backend/swagger/classes_get_by_id.yml
  backend/swagger/classes_post.yml
  backend/swagger/classrooms_delete.yml
  backend/swagger/classrooms_get_all.yml
  backend/swagger/classrooms_get_by_id.yml
  backend/swagger/classrooms_post.yml
  backend/swagger/states_post.yml
  cfg/linter.cfg
  requirements.txt
Labels: enhancement

#27 Ошибка E126 добавлена в исключения для линтера
  cfg/linter.cfg
Labels: bug

#30 #28: добавлено разделение аудиторий и изменены названия корпусов
  sync/addition.py
  sync/deletion.py
  sync/sync.py
Labels: bug

#32 #29: Исправить файлы данных бота и функцию show_is_empty_audience()
  data/lessons.json
  data/levels.json
  main.py
Labels: bug

#33 #31: Добавлены версии пакетов в requirements.txt
  requirements.txt
Labels: enhancement

#35 #34: исправлен запрос для создания связи сущностей
  sync/addition.py
Labels: bug

#38 Добавлена документация к API
  backend/app.py
  backend/swagger/classes_delete.yml
  backend/swagger/classes_get_all.yml
  backend/swagger/classes_get_by_id.yml
  backend/swagger/classes_post.yml
  backend/swagger/classrooms_delete.yml
  backend/swagger/classrooms_get_all.yml
  backend/swagger/classrooms_get_by_id.yml
  backend/swagger/classrooms_post.yml
  backend/swagger/states_post.yml
  docs/README.md
  docs/bmstu-free-api.yaml
Labels: documentation, enhancement

#43 #40: Поменять сообщения от бота на более логичные
  data/messages.json
  main.py
Labels: bug

#44 #36: добавлено тестирование API
  api_tests/conftest.py
  api_tests/test_classes_resources.py
  api_tests/test_classrooms_resources.py
  api_tests/test_db.py
  api_tests/test_states_resources.py
  backend/app.py
  backend/database.py
  requirements.txt
Labels: enhancement

#46 #45: Добавить API тесты в CI
  .github/workflows/pythonci-test.yml
Labels: enhancement
